from pygame.locals import *

# Direction constants
UP = 1
RIGHT = 2
DOWN = 3
LEFT = 4

ACTIVATE = 5

# Movement speed constants

VERY_FAST_SPEED, FAST_SPEED, NORMAL_SPEED, SLOW_SPEED, VERY_SLOW_SPEED = 3, 4, 6, 10, 15

SPEEDS = [VERY_FAST_SPEED, FAST_SPEED, NORMAL_SPEED, SLOW_SPEED, VERY_SLOW_SPEED]

DEFAULT_OBJECT_IMAGE_BASIC_ANIMATION = [[1, 2], [1, 0]]

# World saving constant

PARTY_POSITION_LOCAL_STATE = '__PARTY_POSITION_LOCAL_STATE'
CHARACTERS_LOCAL_STATE = '__CHARACTERS_LOCAL_STATE'
PARTIES_LOCAL_STATE = '__PARTIES_LOCAL_STATE'

# Animated tiles

ANIMATION_PERIOD = 12
